name: Generate APK Only
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Force Build APK
        run: |
          # البحث عن ملف gradlew وتشغيله لبناء APK فقط
          chmod +x $(find . -name gradlew)
          cd $(find . -name android -type d | head -n 1)
          ./gradlew assembleRelease

      - name: Upload Only APK
        uses: actions/upload-artifact@v4
        with:
          name: My_Final_APK
          path: "**/*.apk"
