name: Generate APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm install @react-native-community/cli --save-dev

      - name: Create Android Assets Folder
        run: mkdir -p android/app/src/main/assets

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Final_App_APK
          path: android/app/build/outputs/apk/release/*.apk
